<?php

return [
    'starter' => [
        'plan' => 'Starter',
        'price' => 300000,
        'store_name' => 'Kedai Rona',
        'initials' => 'KR',
        'tagline' => 'Kopi lokal untuk jeda yang hangat.',
        'headline' => 'Temukan rasa nyaman dalam setiap seduhan.',
        'description' => 'Kopi pilihan, camilan rumahan, dan perlengkapan seduh sederhana untuk menemani harimu.',
        'accent' => '#2ca6a4',
        'accent_soft' => '#e3f4f3',
        'category' => 'Kopi & camilan',
        'payment' => 'QRIS otomatis',
        'capacity' => 'Maksimal 50 produk',
        'max_products' => 50,
        'max_payment_gateways' => 1,
        'domain' => 'Subdomain ScriptMedia',
        'layout' => 'simple',
        'catalog_search' => false,
        'catalog_sort' => false,
        'related_products' => false,
        'content_quota' => 1,
        'support' => 'Respons maksimal 24 jam pada hari kerja',
        'shipping' => 'Ongkir dikonfirmasi oleh toko',
        'products' => [
            ['name' => 'Kopi Susu Rona', 'category' => 'Minuman', 'price' => 22000, 'icon' => '☕', 'color' => '#dcefeb'],
            ['name' => 'Kopi Gula Aren', 'category' => 'Minuman', 'price' => 24000, 'icon' => '🥤', 'color' => '#f8e5c3'],
            ['name' => 'Cookies Cokelat', 'category' => 'Camilan', 'price' => 32000, 'icon' => '🍪', 'color' => '#f3dfd2'],
            ['name' => 'Drip Bag Rona', 'category' => 'Kopi', 'price' => 48000, 'icon' => '🫘', 'color' => '#e6e1d5'],
            ['name' => 'Mug Keramik', 'category' => 'Peralatan', 'price' => 69000, 'icon' => '🍵', 'color' => '#dce8f2'],
            ['name' => 'Paket Teman Sore', 'category' => 'Hampers', 'price' => 99000, 'icon' => '🎁', 'color' => '#f7e7d0'],
        ],
    ],
    'standard' => [
        'plan' => 'Standard',
        'price' => 500000,
        'store_name' => 'Shicomp Store',
        'initials' => 'SC',
        'tagline' => 'Perangkat tepat, kerja lebih cepat.',
        'headline' => 'Upgrade ruang kerja dengan pilihan yang tepat.',
        'description' => 'Aksesori komputer dan kebutuhan produktivitas pilihan dengan garansi serta dukungan terpercaya.',
        'accent' => '#f4a300',
        'accent_soft' => '#fff3d6',
        'category' => 'Teknologi & aksesori',
        'payment' => 'QRIS + transfer bank otomatis',
        'capacity' => 'Maksimal 150 produk',
        'max_products' => 150,
        'max_payment_gateways' => 2,
        'domain' => 'Mendukung custom domain',
        'layout' => 'business',
        'catalog_search' => true,
        'catalog_sort' => false,
        'related_products' => true,
        'content_quota' => 3,
        'support' => 'Respons prioritas maksimal 12 jam',
        'shipping' => 'Ongkir dikonfirmasi oleh toko',
        'hero_banner' => '/images/demo/shicomp-standard-hero.png',
        'products' => [
            ['name' => 'Mechanical Keyboard K87', 'category' => 'Keyboard', 'price' => 629000, 'icon' => '⌨️', 'color' => '#dfe8f4'],
            ['name' => 'Wireless Mouse M2', 'category' => 'Mouse', 'price' => 289000, 'icon' => '🖱️', 'color' => '#e5ecef'],
            ['name' => 'Monitor Light Bar', 'category' => 'Workspace', 'price' => 419000, 'icon' => '💡', 'color' => '#fff0c9'],
            ['name' => 'USB-C Hub 7-in-1', 'category' => 'Konektivitas', 'price' => 379000, 'icon' => '🔌', 'color' => '#e6e4f3'],
            ['name' => 'Laptop Stand Pro', 'category' => 'Workspace', 'price' => 339000, 'icon' => '💻', 'color' => '#dcefeb'],
            ['name' => 'Desk Mat Midnight', 'category' => 'Aksesori', 'price' => 179000, 'icon' => '🖥️', 'color' => '#dde3eb'],
        ],
    ],
    'pro' => [
        'plan' => 'Pro',
        'price' => 700000,
        'store_name' => 'Nara Atelier',
        'initials' => 'NA',
        'tagline' => 'Curated pieces for considered living.',
        'headline' => 'Ruang yang bercerita, dibuat khusus untukmu.',
        'description' => 'Koleksi interior kontemporer dengan pengalaman belanja premium dan tampilan yang sepenuhnya terkustomisasi.',
        'accent' => '#c66a4a',
        'accent_soft' => '#f7e7df',
        'category' => 'Interior premium',
        'payment' => 'Multi payment gateway',
        'capacity' => 'Produk unlimited',
        'max_products' => null,
        'max_payment_gateways' => null,
        'domain' => 'Custom domain & desain penuh',
        'layout' => 'editorial',
        'catalog_search' => true,
        'catalog_sort' => true,
        'related_products' => true,
        'content_quota' => 5,
        'support' => 'Respons maksimal 6 jam, termasuk akhir pekan',
        'shipping' => 'Siap integrasi ongkir otomatis real-time',
        'hero_banner' => '/images/demo/nara-pro-hero.png',
        'products' => [
            ['name' => 'Lumi Lounge Chair', 'category' => 'Furniture', 'price' => 4850000, 'icon' => '🪑', 'color' => '#eaded4'],
            ['name' => 'Sora Pendant Lamp', 'category' => 'Lighting', 'price' => 2290000, 'icon' => '🏮', 'color' => '#f1e4c8'],
            ['name' => 'Arka Side Table', 'category' => 'Furniture', 'price' => 1750000, 'icon' => '🪵', 'color' => '#e3ddd0'],
            ['name' => 'Terra Ceramic Set', 'category' => 'Decor', 'price' => 890000, 'icon' => '🏺', 'color' => '#eee0d5'],
            ['name' => 'Nami Woven Rug', 'category' => 'Textile', 'price' => 3190000, 'icon' => '🧶', 'color' => '#e8dfcf'],
            ['name' => 'Awan Linen Throw', 'category' => 'Textile', 'price' => 790000, 'icon' => '🛋️', 'color' => '#e1e7e5'],
        ],
    ],
];
