<x-layouts::app title="Laporan penjualan">
    <div><x-ui.badge variant="navy">Analitik</x-ui.badge><h1 class="mt-3 text-3xl text-navy">Laporan penjualan</h1><p class="mt-2 text-ink-soft">Ringkasan order dan revenue berdasarkan periode.</p></div>
    <x-ui.card class="mt-8"><form method="GET" class="flex flex-col gap-4 sm:flex-row sm:items-end"><label class="grid gap-2 text-sm font-semibold text-navy">Dari<input type="date" name="from" value="{{ $from->toDateString() }}" class="rounded-xl border border-line px-4 py-3 font-normal cursor-pointer"></label><label class="grid gap-2 text-sm font-semibold text-navy">Sampai<input type="date" name="to" value="{{ $to->toDateString() }}" class="rounded-xl border border-line px-4 py-3 font-normal cursor-pointer"></label><x-ui.loading-button loading-label="Memuat..." variant="navy" class="cursor-pointer">Terapkan</x-ui.loading-button></form></x-ui.card>
    <div class="mt-6 grid gap-5 md:grid-cols-3"><x-ui.card><x-ui.badge>Order</x-ui.badge><p class="mt-5 text-4xl font-semibold text-navy">{{ $orderCount }}</p></x-ui.card><x-ui.card><x-ui.badge variant="orange">Selesai</x-ui.badge><p class="mt-5 text-4xl font-semibold text-navy">{{ $completedOrderCount }}</p></x-ui.card><x-ui.card><x-ui.badge variant="navy">Revenue</x-ui.badge><p class="mt-5 text-3xl font-semibold text-navy">Rp{{ number_format($revenue, 0, ',', '.') }}</p></x-ui.card></div>

    @if ($orders->isEmpty())
        <x-ui.empty-state class="mt-6" icon="report" title="Belum ada data pada periode ini" description="Ubah rentang tanggal atau tunggu sampai transaksi baru tercatat untuk melihat laporan penjualan." />
    @else
        <x-ui.card class="mt-6" :padding="false"><div class="overflow-x-auto"><table class="w-full min-w-[40rem] text-left text-sm"><thead class="border-b border-line bg-offwhite text-xs tracking-wide text-ink-soft uppercase"><tr><th class="px-6 py-4">Order</th><th class="px-6 py-4">Tanggal</th><th class="px-6 py-4">Status</th><th class="px-6 py-4">Pembayaran</th><th class="px-6 py-4">Total</th></tr></thead><tbody class="divide-y divide-line">@foreach ($orders as $order)<tr><td class="px-6 py-4 font-semibold text-navy">{{ $order->number }}</td><td class="px-6 py-4 text-ink-soft">{{ $order->placed_at->format('d M Y') }}</td><td class="px-6 py-4">{{ ucfirst($order->status) }}</td><td class="px-6 py-4">{{ ucfirst($order->payment_status) }}</td><td class="px-6 py-4">Rp{{ number_format((float) $order->total, 0, ',', '.') }}</td></tr>@endforeach</tbody></table></div></x-ui.card>
        <div class="mt-8">{{ $orders->links() }}</div>
    @endif
</x-layouts::app>
