<x-layouts::app title="Order">
    <div><x-ui.badge variant="orange">Fulfillment</x-ui.badge><h1 class="mt-3 text-3xl text-navy">Order masuk</h1><p class="mt-2 text-ink-soft">Pantau dan proses pesanan pelanggan.</p></div>
    <div class="mt-8 flex flex-wrap gap-2"><a href="{{ route('admin.orders.index') }}" class="rounded-full px-4 py-2 text-sm font-semibold transition {{ $status === '' ? 'bg-navy text-white' : 'border border-line bg-white text-ink-soft hover:text-navy' }}">Semua</a>@foreach (\App\Models\Order::STATUSES as $orderStatus)<a href="{{ route('admin.orders.index', ['status' => $orderStatus]) }}" class="rounded-full px-4 py-2 text-sm font-semibold transition {{ $status === $orderStatus ? 'bg-navy text-white' : 'border border-line bg-white text-ink-soft hover:text-navy' }}">{{ ucfirst($orderStatus) }}</a>@endforeach</div>

    @if ($orders->isEmpty())
        <x-ui.empty-state class="mt-5" icon="order" title="{{ $status === '' ? 'Belum ada order masuk' : 'Tidak ada order dengan status ini' }}" description="{{ $status === '' ? 'Order pelanggan akan muncul di sini setelah checkout berhasil.' : 'Pilih status lain untuk melihat order yang tersedia.' }}" :action-href="$status === '' ? route('home') : route('admin.orders.index')" :action-label="$status === '' ? 'Lihat storefront' : 'Lihat semua order'" />
    @else
        <x-ui.card class="mt-5" :padding="false"><div class="overflow-x-auto"><table class="w-full min-w-[48rem] text-left text-sm"><thead class="border-b border-line bg-offwhite text-xs tracking-wide text-ink-soft uppercase"><tr><th class="px-6 py-4">Order</th><th class="px-6 py-4">Pelanggan</th><th class="px-6 py-4">Tanggal</th><th class="px-6 py-4">Total</th><th class="px-6 py-4">Status</th><th class="px-6 py-4"></th></tr></thead><tbody class="divide-y divide-line">@foreach ($orders as $order)<tr><td class="px-6 py-4 font-semibold text-navy">{{ $order->number }}</td><td class="px-6 py-4"><span class="block text-navy">{{ $order->customer_name }}</span><span class="text-xs text-ink-soft">{{ $order->customer_email }}</span></td><td class="px-6 py-4 text-ink-soft">{{ $order->placed_at->format('d M Y H:i') }}</td><td class="px-6 py-4">Rp{{ number_format((float) $order->total, 0, ',', '.') }}</td><td class="px-6 py-4"><x-ui.badge variant="{{ $order->status === 'pending' ? 'orange' : 'tosca' }}">{{ ucfirst($order->status) }}</x-ui.badge></td><td class="px-6 py-4 text-right"><a href="{{ route('admin.orders.show', $order) }}" class="font-semibold text-tosca">Detail</a></td></tr>@endforeach</tbody></table></div></x-ui.card>
        <div class="mt-8">{{ $orders->links() }}</div>
    @endif
</x-layouts::app>
