<x-layouts::app title="Order Sewa">
    <div class="space-y-8">
        <x-ui.section-header eyebrow="Onboarding klien" title="Order sewa toko" description="Periksa pembayaran dan mulai provisioning hanya untuk order yang sudah lunas." />
        @if (session('status'))<div class="rounded-xl border border-tosca/30 bg-tosca-tint px-5 py-4 text-sm text-navy">{{ session('status') }}</div>@endif
        <x-ui.card :padding="false" class="overflow-hidden">
            <div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-offwhite text-xs tracking-wide text-ink-soft uppercase"><tr><th class="px-5 py-4">Order</th><th class="px-5 py-4">Klien</th><th class="px-5 py-4">Plan</th><th class="px-5 py-4">Total</th><th class="px-5 py-4">Status</th><th class="px-5 py-4 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-line">@forelse ($orders as $order)<tr><td class="px-5 py-4"><p class="font-semibold text-navy">{{ $order->number }}</p><p class="mt-1 text-xs text-ink-soft">{{ $order->business_name }} · {{ $order->desired_subdomain }}.scriptmedia.id</p></td><td class="px-5 py-4"><p>{{ $order->user->name }}</p><p class="mt-1 text-xs text-ink-soft">{{ $order->user->email }}</p></td><td class="px-5 py-4">{{ str($order->plan->name)->title() }}<p class="mt-1 text-xs text-ink-soft">{{ $order->billing_cycle === 'annual' ? 'Tahunan' : 'Bulanan' }}</p></td><td class="px-5 py-4">Rp{{ number_format((float) $order->amount, 0, ',', '.') }}</td><td class="px-5 py-4"><x-ui.badge :variant="$order->status === 'ready' ? 'tosca' : 'orange'">{{ str($order->status)->replace('_', ' ')->title() }}</x-ui.badge></td><td class="px-5 py-4 text-right">@if ($order->status === 'paid' && ! $order->tenant_id)<form method="POST" action="{{ route('admin.rental-orders.provision', $order) }}">@csrf<x-ui.button type="submit" onclick="return confirm('Mulai provisioning toko ini?')">Mulai provisioning</x-ui.button></form>@elseif ($order->tenant)<a href="{{ route('admin.tenants.index') }}" class="font-semibold text-tosca">Lihat tenant</a>@else<span class="text-xs text-ink-soft">Menunggu pembayaran</span>@endif</td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center text-ink-soft">Belum ada order sewa.</td></tr>@endforelse</tbody></table></div>
        </x-ui.card>
        {{ $orders->links() }}
    </div>
</x-layouts::app>
